name: gourmet_pro_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  get: ^4.7.2
  get_storage: ^2.1.1
  shared_preferences: ^2.2.3
  file_picker: ^10.3.3
  flutter_map: ^8.2.2
  flutter_osm_plugin: ^1.4.2
  flutter_widget_from_html_core: ^0.17.0
  http: ^1.5.0
  image_picker: ^1.2.0
  latlong2: ^0.9.1
  qr_flutter: ^4.1.0
  socket_io_client: ^3.1.2
  url_launcher: ^6.3.2
  jwt_decoder: ^2.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
